#!/usr/bin/env python3
"""Assemble index.html and js/deck.js.

- index.html  = index.template.html with js/app.js inlined. The app's custom
  template runtime (js/dc-runtime.js) reads the component <script>'s text and
  compiles it itself, so app.js can't be a normal external <script src>.
- js/deck.js  = vocabulary.json as a plain script (window.WN_VOCAB), so the
  app works offline and from file:// with no fetch.

Edit css/app.css, js/app.js and vocabulary.json as the sources of truth, then
re-run this script.
"""
import json, pathlib

root = pathlib.Path(__file__).parent

vocab = json.loads((root / "vocabulary.json").read_text(encoding="utf-8"))
compact = {
    "categories": vocab["categories"],
    "cards": [{k: c[k] for k in ("id", "deck", "fr", "en", "type", "ex", "ipa") if c.get(k)} for c in vocab["cards"]],
}
(root / "js" / "deck.js").write_text(
    "// generated by build.py from vocabulary.json, do not edit\nwindow.WN_VOCAB=" +
    json.dumps(compact, ensure_ascii=False, separators=(",", ":")) + ";\n", encoding="utf-8")

template = (root / "index.template.html").read_text(encoding="utf-8")
app_js = (root / "js" / "app.js").read_text(encoding="utf-8")
(root / "index.html").write_text(template.replace("<!--APP_JS-->", "\n" + app_js), encoding="utf-8")
print("wrote js/deck.js and index.html")
